config:
  args: ["clearnode"]
  logLevel: info
  database:
    driver: postgres
    host: postgresql.core
    port: 5432
    name: clearnet_prod
    user: clearnet_prod_admin
  envSecret: ""
  extraEnvs:
    POLYGON_CUSTODY_CONTRACT_ADDRESS: "0x4C8Bd8877C3b403BA9f9ECfaAD910AF0d8CA2c4D"
    POLYGON_ADJUDICATOR_ADDRESS: "0x5F4A4B1D293A973a1Bc0daD3BB3692Bd51058FCF"
    WORLD_CHAIN_CUSTODY_CONTRACT_ADDRESS: "0x1096644156Ed58BF596e67d35827Adc97A25D940"
    WORLD_CHAIN_ADJUDICATOR_ADDRESS: "0xEd44dba5ECB7928032649EF0075258FA3aca508B"
    FLOW_CUSTODY_CONTRACT_ADDRESS: "0x6258dCa1DF894980a8778197c60893a9fa2b5eF8"
    FLOW_ADJUDICATOR_ADDRESS: "0xEd44dba5ECB7928032649EF0075258FA3aca508B"
    MSG_EXPIRY_TIME: "60"

image:
  repository: ghcr.io/erc7824/nitrolite/clearnode
  tag: 0.0.1-rc.9

service:
  http:
    enabled: true
    port: 8000
    path: /

metrics:
  enabled: true
  podmonitoring:
    enabled: true
  port: 4242
  endpoint: "/metrics"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 100Mi

autoscaling:
  enabled: false

networking:
  externalHostname: clearnet.yellow.com
  tlsClusterIssuer: zerossl-prod
  gateway:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    tls:
      enabled: true

imagePullSecret: ghcr-pull
