config:
  database:
    password: ref+tfstategs://terraform-state-deploy/gke-uat-postgresql-admin/default.tfstate/output.postgresql_user_passwords["clearnet_prod_admin"]
  secretEnvs:
    BROKER_PRIVATE_KEY: ref+gcpsecrets://ynet-stage/clearnet-prod-broker-private-key?version=latest
    POLYGON_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-prod-polygon-infura-url?version=latest
    WORLD_CHAIN_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-prod-worldchain-infura-url?version=latest
    FLOW_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-prod-flow-infura-url?version=latest
