# Combined zkMed + vlayer services
# Includes vlayer infrastructure and zkMed application services

include:
  - srcs/foundry/vlayer/docker-compose.devnet.yaml

services:
  # ==================================================================================
  # ZKMED APPLICATION SERVICES
  # ==================================================================================

  # Contract Deployer
  zkmed-contracts:
    build:
      context: ./srcs/foundry
      dockerfile: Dockerfile.deployer
    container_name: zkmed-contracts
    volumes:
      - contract-artifacts:/app/out:rw
    environment:
      - RPC_URL=http://anvil-l2-mantle:8545
      - RPC_HOST=anvil-l2-mantle
      - CHAIN_ID=31339
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    restart: "no"
    depends_on:
      anvil-l2-mantle:
        condition: service_started
    networks:
      - zkmed-network # Renamed from vlayer-network

  # Next.js Frontend Container  
  zkmed-frontend:
    build:
      context: ./srcs/nextjs
      dockerfile: Dockerfile
    container_name: zkmed-frontend
    ports:
      - "3001:3000"
    depends_on:
      zkmed-contracts:
        condition: service_completed_successfully
      vlayer-call-server:
        condition: service_healthy
      notary-server:
        condition: service_healthy
    volumes:
      - contract-artifacts:/app/contracts:ro
      - ./srcs/nextjs:/app:rw
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CHAIN_ID=31337
      - NEXT_PUBLIC_RPC_URL=http://anvil-l2-mantle:8545
      - NEXT_PUBLIC_THIRDWEB_CLIENT_ID=b928ddd875d3769c8652f348e29a52c5
      - NEXT_TELEMETRY_DISABLED=1
      # vlayer environment
      - VLAYER_ENV=dev
      - CHAIN_NAME=anvil
      - PROVER_URL=http://vlayer-call-server:3000
      - JSON_RPC_URL=http://anvil-l2-mantle:8545
      - EXAMPLES_TEST_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - NOTARY_URL=http://notary-server:7047
      - WS_PROXY_URL=ws://localhost:3003
      - EMAIL_SERVICE_URL=https://email-example-inbox.s3.us-east-2.amazonaws.com
      # smart wallet factory
      - SMART_WALLET_FACTORY_MANTLE=0x06224c9387a352a953d6224bfff134c3dd247313
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - zkmed-network # Renamed from vlayer-network

volumes:
  contract-artifacts:
    driver: local

networks:
  zkmed-network: # Renamed from vlayer-network
    name: zkmed-network # Renamed from vlayer-network
    driver: bridge