version: '3.8'

services:
  # Contract Deployer and Demo Setup 
  zkmed-contracts:
    build:
      context: ./containers/contracts
      dockerfile: Dockerfile
    container_name: zkmed-contracts
    depends_on:
      - anvil  # From vlayer docker-compose.devnet.yaml
    volumes:
      - ./demo-data:/app/demo-data
      - ./packages/foundry:/app/foundry
      - contract-artifacts:/app/artifacts
      - ./packages/foundry/vlayer:/app/vlayer
    environment:
      - RPC_URL=http://anvil:8545
      - CHAIN_ID=31337
      - DEMO_MODE=true
      - VLAYER_CALL_SERVER=http://call_server:3000
      - VLAYER_VDNS_SERVER=http://vdns_server:3002
      - VLAYER_NOTARY_SERVER=http://notary-server:7047
      # Demo account private keys (anvil default accounts)
      - PRIVATE_KEY_INSURER=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - PRIVATE_KEY_HOSPITAL=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - PRIVATE_KEY_PATIENT=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
      - PRIVATE_KEY_ADMIN=0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
    restart: "no"
    working_dir: /app/foundry
    command: ["./scripts/deploy-demo.sh"]
    networks:
      - vlayer-network

  # Next.js Frontend Container  
  zkmed-frontend:
    build:
      context: ./packages/nextjs
      dockerfile: Dockerfile
    container_name: zkmed-frontend
    ports:
      - "3000:3000"
    depends_on:
      zkmed-contracts:
        condition: service_completed_successfully
    volumes:
      - contract-artifacts:/app/contracts:ro
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_RPC_URL=http://localhost:8545
      - NEXT_PUBLIC_CHAIN_ID=31337
      - NEXT_PUBLIC_DEMO_MODE=true
      # Demo account addresses (corresponding to private keys above)
      - NEXT_PUBLIC_DEMO_INSURER=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
      - NEXT_PUBLIC_DEMO_HOSPITAL=0x70997970c51812dc3a010c7d01b50e0d17dc79c8
      - NEXT_PUBLIC_DEMO_PATIENT=0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc
      # vlayer service endpoints
      - NEXT_PUBLIC_VLAYER_CALL_SERVER=http://localhost:3000
      - NEXT_PUBLIC_VLAYER_VDNS_SERVER=http://localhost:3002
      - NEXT_PUBLIC_VLAYER_NOTARY_SERVER=http://localhost:7047
      - NEXT_PUBLIC_VLAYER_WEBSOCKET_PROXY=http://localhost:3003
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vlayer-network

  # Demo Data API Service
  zkmed-demo-api:
    build:
      context: ./containers/demo-api
      dockerfile: Dockerfile
    container_name: zkmed-demo-api
    ports:
      - "8080:8080"
    depends_on:
      - zkmed-contracts
    volumes:
      - ./demo-data:/app/demo-data:ro
      - contract-artifacts:/app/contracts:ro
    environment:
      - RPC_URL=http://anvil:8545
      - CHAIN_ID=31337
      - DEMO_ACCOUNTS_FILE=/app/demo-data/accounts.json
    restart: always
    networks:
      - vlayer-network

  # Nginx Reverse Proxy for Demo Access
  zkmed-proxy:
    image: nginx:alpine
    container_name: zkmed-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - zkmed-frontend
      - zkmed-demo-api
    restart: always
    networks:
      - vlayer-network

volumes:
  contract-artifacts:
    driver: local

# Use the same network as vlayer services
networks:
  vlayer-network:
    external: true 