{{- $http := .Values.service.http }}
{{- if and .Values.networking.gateway.enabled $http.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "clearnode.common.fullname" . }}
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Release.Namespace }}
      name: {{ include "clearnode.common.fullname" . }}
      port: 443
      sectionName: https
  hostnames:
    - {{ .Values.networking.externalHostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ $http.path }}
      backendRefs:
        - name: {{ include "clearnode.common.fullname" . }}
          port: {{ default $http.port $http.internalPort }}
{{- end }}
