{{- if .Values.networking.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-http-redirect" (include "clearnode.common.fullname" .) }}
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Release.Namespace }}
      name: {{ include "clearnode.common.fullname" . }}
      port: 80
      sectionName: http
  hostnames:
    - {{ .Values.networking.externalHostname }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
          hostname: {{ .Values.networking.externalHostname }}
{{- end }}
