{{- if .Values.config.secretEnvs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clearnode.common.fullname" . }}-secret-env
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
{{- with .Values.config.database }}
{{- if eq .driver "postgres" }}
  CLEARNODE_DATABASE_URL: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=%s" .user .password .host (print .port) .name .sslmode | b64enc }}
{{- end }}
{{- if eq .driver "sqlite" }}
  CLEARNODE_DATABASE_URL: {{ printf "file:%s" .path | b64enc }}
{{- end }}
{{- end }}
{{- range $key, $value := .Values.config.secretEnvs  }}
  {{- $key | nindent 2 }}: {{ $value | print | b64enc }}
{{- end }}
{{- end }}
