config:
  database:
    password: ref+tfstategs://terraform-state-deploy/gke-uat-postgresql-admin/default.tfstate/output.postgresql_user_passwords["clearnet_uat_admin"]
  secretEnvs:
    BROKER_PRIVATE_KEY: ref+gcpsecrets://ynet-stage/clearnet-uat-broker-private-key?version=latest
    POLYGON_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-uat-polygon-infura-url?version=latest
    ETH_SEPOLIA_INFURA_URL: ref+gcpsecrets://ynet-stage/clearnet-uat-eth-sepolia-infura-url?version=latest
